[versions]
agp = "8.3.0-rc02"
bcprovJdk18on = "1.77"
sshj = "0.38.0"

[libraries]
bcprov-jdk18on = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bcprovJdk18on" }
sshj = { module = "com.hierynomus:sshj", version.ref = "sshj" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }

